### ISSUE TITLE
How to read data from a database?

### ISSUE THREAD

**Issue by ZedZipDev** [doxakis/HdbscanSharp#11]
Thank you for the implementation.
I have a database (SQL Server or PostgreSQL etc) and one table contains text field.
I'd like to read the texts from this table but not from the file set (as in the sample) and then analyze and detect clusters.
Can you advise something? Thanx!

**Comment by doxakis** [comment]
Hi,

currently, there are 2 ways to use the algorithm and it's by providing the DataSet as an double[][] or the distance matrix (double[][]).
I will work on a simpler way to call it for text content. (inspired by the project DocumentClusteringExample but without using text files)
It's not commit yet, but I found a way to better represent text data with sparse data structure.
It should help reduce memory consumption and speed up calculating the distances.

I don't know how much rows you expect to process and the number of words per text field. I don't know if it will work well for you.
Is it possible to give me more infos? (approximation of number of rows, number of word per text content, language being used, the number of threads you can use)

I'm asking for the language because in the project DocumentClusteringExample, I used a list of stop words in english and it helps removing some common words that mean nothing. (e.g. a, the, is, and)

If you have too many rows or words, one approach could be to split the rows in multiple smaller batches and run the algorithm for each batch. (The algorithm does not scale linearly)
At least, it can return clusters while using less memory, CPU and time.

Thanks!

**Comment by doxakis** [comment]
Hi,

I did the changes I was referring to in the library and published a new version (2.0.0) on nuget.
I also created another repo [TextClustering](https://github.com/doxakis/TextClustering) which is easier to use for text clustering.
I think the example should help you achieve what you describe.
Let me know how it goes.

Thanks

**Comment by doxakis** [comment]
Hi, I will close the issue for now. Feel free to open it again if you have any question.
